title: Puck Off
email: puckoff@skoggygames.com
description: > # this means to ignore newlines until "baseurl:"
  Puck Off is a video game inspired by the old classic table-hockey games
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://puckoffgame.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: skoggygames
twitter_username_personal: erikskogl
github_username:  eriksk
copyright: Copyright &copy Erik Skoglund - Skoggy Games 2017

disqus:
  shortname: puckoffgame

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
